### ISSUE TITLE
Its element type 'ReactElement<any, any> | Component<IIframe, any, any> | null' is not a valid JSX element.

### ISSUE THREAD

**Issue by HT-Moh** [robbestad/react-iframe#113]
Type issue, maybe due to the ReactNode' on React 18 

` "react-iframe": "^1.8.0"`
` "react": "^18.0.0",
`next``

![image](https://user-images.githubusercontent.com/34759569/162577457-e1dc57aa-c088-4530-b32c-8cab9c93a824.png)

Maybe related: 

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by eps1lon** [comment]
Explanation and workaround can be found in https://github.com/react-native-svg/react-native-svg/issues/1741

**Comment by HT-Moh** [comment]
Solution worked for me: 
Update packages react and react-dom and types 
 "react": "^18.0.0",
 "react-dom": "^18.0.0",
 @types/react": "^18.0.4",
 @types/react-dom": "^18.0.0"


```
"@types/react": "^18.0.4",
Add the following to `package.json` 
```  
"resolutions": {
    "react-i18next": ">=11.16.4"
  }
```
