### ISSUE TITLE
"styles" is not handled properly

### ISSUE THREAD

**Issue by denizdogan** [robbestad/react-iframe#51]
Reproduce:

```jsx
ReactDOM.render(
  <Iframe url='https://www.test-cors.org/'
                  width='100%'
                  height='100%'
                  styles={{ borderWidth: '0' }}
                  position='relative'/>,
  root
)
```

The result is an iframe with no "border-width" set, with an extra attribute styles="[object Object]"

**Comment by vanduongit** [comment]
why don't you implement styles properties which you offer?

**Comment by jQwotos** [comment]
One workaround would be to use [emotion](https://emotion.sh/docs/introduction) and style the `Iframe` component

```
import styled from 'react-emotion';

const BorderLessIframe = styled(Iframe)`
    border-width: 0;
`;

ReactDOM.render(
    <BorderLessIframe url='https://www.test-cors.org/'
                  width='100%'
                  height='100%'
                  styles={{ borderWidth: '0' }}
                  position='relative'/>,
  root
);
```

**Comment by dzienisz** [comment]
I have the same problem

**Comment by sainijagjit** [comment]
react-emotion library is now changed. Latest working code

import styled from '@emotion/styled';
const BorderLessIframe = styled(Iframe)`
  border-width: 0;
`;

<BorderLessIframe
                url={`${window.location.origin}/bial-t2/index.html`}
                loading="We are fetching maps, please wait"
                width="100%"
                height="100%"
                display="initial"
                position="absolute"
              />

**Comment by robbestad** [comment]
Fixed now thanks to @nagamejun
