### ISSUE TITLE
Not supported on IE browser and shows blank page 

### ISSUE THREAD

**Issue by krishgopal24** [robbestad/react-iframe#53]
I have used the Iframe component from React/iframe. Please resolve this issue;

**Comment by galoi** [comment]
@krishgopal24 
Which windows OS and IE version?
I was able to use Iframe component without trouble on IE11, both windows 7 and 10

**Comment by canujohann** [comment]
Same here when trying to render an Iframe containing a PDF (PDF file is downloaded instead of beeing shown)

**Comment by robbestad** [comment]
IE is deprecated, so no fix coming 😈
