### ISSUE TITLE
Sandbox type does not allow multiple values

### ISSUE THREAD

**Issue by nmoinvaz** [robbestad/react-iframe#78]
The typescript definition for the `sandbox` property is a list of possible string values. 

https://github.com/svenanders/react-iframe/blob/66a082995f77b1f0f44b3dcc77bcda7081719a42/src/types.d.ts#L26

I think it should just be a `string`. Currently that does not allow you to specify multiple values such as:

```
sandbox="allow-forms allow-scripts"
```
Maybe there is another way to specify it and keep typescript happy?

![image](https://user-images.githubusercontent.com/1364432/90850101-ab922c00-e325-11ea-8e87-ebcf0a9b60dd.png)

**Comment by Sensiblemnd** [comment]
sandbox
Applies extra restrictions to the content in the frame. The value of the attribute can either be empty to apply all restrictions, **or space-separated tokens to lift particular restrictions:**

**Comment by robbestad** [comment]
It does not allow multiple values as a string. However, you can add it as an array. Example given in `README.md` and in the demo.
