### ISSUE TITLE
Render HTML file from src

### ISSUE THREAD

**Issue by klaudiuszfraj** [robbestad/react-iframe#82]
Hi, when I try to render Iframe with HTML file in src director, it's renders iframe tag with my whole application.
it doesn't matter how I provide the path - src={'./test.html'} works exactly the same.
External links like url="http://www.youtube.com/embed/xDMP3i36naA" works fine

<Iframe src={'src/components/Iframe/test.html'}
                width="450px"
                height="450px"
                id="myId"
                className="myClassname"
                display="initial"
                position="relative"/>

**Comment by robbestad** [comment]
Iframes doesn't allow relative urls, so you have to provide an absolute url.
